// export enum SessionStatus {
//   CREATED = 'CREATED',
//   // CONFIRMED = 'CONFIRMED',
//   HELD = 'HELD',
//   // DELIVERED = 'DELIVERED',
//   REVISION_REQUESTED = 'REVISION_REQUESTED',
//   // APPROVED = 'APPROVED',
//   // RELEASED = 'RELEASED',
//   // DISPUTED = 'DISPUTED',
//   // REFUNDED = 'REFUNDED',

//   EXPIRED = 'EXPIRED',
//   JOINED = 'JOINED',
//   PENDING_CONFIRMATION = 'PENDING_CONFIRMATION',
//   COMPLETED = 'COMPLETED',
//   AWAITING_CLIENT_APPROVAL = 'AWAITING_CLIENT_APPROVAL',

//   // FUNDED = 'FUNDED',
// }
export enum SessionStatus {
  CREATED = 'CREATED',
  HELD = 'HELD',
  REVISION_REQUESTED = 'REVISION_REQUESTED',
  DISPUTED = 'DISPUTED',
  EXPIRED = 'EXPIRED',
  JOINED = 'JOINED',
  PENDING_CONFIRMATION = 'PENDING_CONFIRMATION',
  COMPLETED = 'COMPLETED',
  AWAITING_CLIENT_APPROVAL = 'AWAITING_CLIENT_APPROVAL',
}
